import express from "express";
import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { createClient } from "@supabase/supabase-js";

const router = express.Router();

// Supabase client (server-side)
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

/* =====================
   VAT EXPORT CSV
===================== */
router.get("/vat/csv/:companyId", async (req, res) => {
  const { companyId } = req.params;

  try {
    const { data: rows, error } = await supabase
      .from("ledger_lines")
      .select(`ledger_entries(date), credit, debit, accounts(code)`)
      .eq("ledger_entries.company_id", companyId)
      .eq("ledger_entries.status", "posted")
      .eq("accounts.code", 2100)
      .order("ledger_entries.date", { ascending: true });

    if (error) throw error;

    const csvHeader = "Month,VAT Collected (NGN)\n";
    const csvRows = rows.map(r => {
      const month = new Date(r.ledger_entries.date).toLocaleString("default", {
        month: "long",
        year: "numeric"
      });
      const amount = Number(r.credit || 0).toFixed(2);
      return `${month},${amount}`;
    });

    res.setHeader("Content-Disposition", "attachment; filename=VAT_Report.csv");
    res.setHeader("Content-Type", "text/csv");
    res.send(csvHeader + csvRows.join("\n"));

  } catch (err) {
    console.error("VAT CSV ERROR:", err);
    res.status(500).json({ error: "VAT CSV export failed" });
  }
});

/* =====================
   VAT EXPORT PDF (with company details)
===================== */
router.get("/vat/pdf/:companyId", async (req, res) => {
  const { companyId } = req.params;

  try {
    // 1️⃣ VAT DATA
    const { data: vatRows, error: vatErr } = await supabase
      .from("ledger_lines")
      .select(`ledger_entries(date), credit, debit, accounts(code)`)
      .eq("ledger_entries.company_id", companyId)
      .eq("ledger_entries.status", "posted")
      .eq("accounts.code", 2100)
      .order("ledger_entries.date", { ascending: true });

    if (vatErr) throw vatErr;

    // 2️⃣ COMPANY INFO
    const { data: compData, error: compErr } = await supabase
      .from("companies")
      .select("name, tin, rc, industry")
      .eq("id", companyId)
      .single();

    if (compErr) throw compErr;

    const company = compData || {
      name: "Registered Business Name",
      tin: "TIN-XXXXXXXX",
      address: "Company Registered Address",
      currency: "NGN",
    };

    const doc = new PDFDocument({ size: "A4", margin: 50 });

    res.setHeader("Content-Disposition", "attachment; filename=VAT_Report.pdf");
    res.setHeader("Content-Type", "application/pdf");

    doc.pipe(res);

    /* ===== HEADER ===== */
    const logoPath = path.join(process.cwd(), "public", "9jatax-logo.png");
    if (fs.existsSync(logoPath)) {
      doc.image(logoPath, 50, 40, { width: 90 });
    }

    doc
      .fontSize(10)
      .fillColor("#6b7280")
      .text("Generated by 9jatax Accounting Software", 50, 115);

    doc
      .fontSize(20)
      .fillColor("#111827")
      .text("VALUE ADDED TAX (VAT) REPORT", { align: "right" });

    doc.moveDown(2);

    /* ===== COMPANY BLOCK ===== */
    doc
      .fontSize(11)
      .fillColor("#111827")
      .text(`Taxpayer Name: ${company.name}`)
      .text(`Tax Identification Number (TIN): ${company.tin}`)
      .text(`Registration Number (RC): ${company.rc || "-"}`)
      .text(`Industry: ${company.industry || "-"}`)
      .text(`Report Generated: ${new Date().toLocaleDateString()}`)
      .text("Currency: NGN");

    doc.moveDown(1.5);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(1);

    /* ===== TABLE HEADER ===== */
    doc
      .fontSize(12)
      .fillColor("#111827")
      .text("Reporting Month", 60, doc.y, { continued: true })
      .text("VAT Amount (₦)", 350);

    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.8);

    /* ===== TABLE BODY ===== */
    let totalVAT = 0;
    vatRows.forEach(r => {
      const month = new Date(r.

ledger_entries.date).toLocaleString("default", {
        month: "long",
        year: "numeric"
      });
      const amount = Number(r.credit || 0);
      totalVAT += amount;

      doc
        .fontSize(11)
        .fillColor("#1f2937")
        .text(month, 60, doc.y, { continued: true })
        .text(
          `₦${amount.toLocaleString(undefined, {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2
          })}`,
          350
        );

      doc.moveDown(0.6);
    });

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(1);

    /* ===== TOTAL ===== */
    doc
      .fontSize(14)
      .fillColor("#111827")
      .text(
        `TOTAL VAT PAYABLE: ₦${totalVAT.toLocaleString(undefined, {
          minimumFractionDigits: 2,
          maximumFractionDigits: 2
        })}`,
        { align: "right" }
      );

    /* ===== FOOTER ===== */
    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor("#6b7280")
      .text(
        "This report is system-generated via 9jatax Accounting Software. Figures are based on posted ledger entries only.",
        { align: "center" }
      );

    doc.end();

  } catch (err) {
    console.error("VAT PDF ERROR:", err);
    res.status(500).json({ error: "VAT PDF generation failed" });
  }
});

export default router;